spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shift_planner
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  flyway:
    locations: classpath:db/migration
server:
  port: 8088
  servlet:
    context-path:
springdoc:
  default-produces-media-type: application/json